application:    workout-buddy-app
version:        1
runtime:        python27
api_version:    1
threadsafe:     yes

handlers:
    #- url:          /(.*\.css)$
    #  static_file:   static/assets/css/\1
- url:          /static
  static_dir:   static

- url:          /tasks/analyze
  script:       main.app
  login:        admin

- url:          /.*
  script:       main.app

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
